pipelines:
    branches:
      master:
        - step:
            name: Sync GitHub Mirror
            image: alpine/git:latest
            clone:
                enabled: false
            script:
                - git clone --bare git@bitbucket.org:linn_systems/linn_public_api_specs.git --branch master
                - cd linn_public_api_specs.git
                - git push --force git@github.com:LinnSystems/PublicApiSpecs.git master:main
        - step:
            name: Readme API sync
            image: node:14
            clone:
                enabled: false
            script:
                - git clone git@bitbucket.org:linn_systems/linn_public_api_specs.git --branch master
                - cd linn_public_api_specs
                - npx rdme@v8 openapi '2.0/authenticate.yml' --key=$key --id=6399a5c4268d5f0985d4cead
                - npx rdme@v8 openapi '2.0/countries.json' --key=$key --id=6426bc4c00c98e00433bae06
                - npx rdme@v8 openapi '2.0/inventory.json' --key=$key --id=63a18738dd3627008a5d7e0b
                - npx rdme@v8 openapi '2.0/locations.yml' --key=$key --id=6426bc76be686f003c05e680
                - npx rdme@v8 openapi '2.0/orders.json' --key=$key --id=6426bcb1b396350011044372
                - npx rdme@v8 openapi '2.0/stock.json' --key=$key --id=64413eb53657d40066923c92
                - npx rdme@v8 openapi '1.0/dashboards.json' --key=$key --id=645b965ee0f2960acb847481
                - npx rdme@v8 openapi '1.0/email.json' --key=$key --id=645bae620b0c650ab6a09182
                - npx rdme@v8 openapi '1.0/genericlistings.json' --key=$key --id=6464e9b6184fd9013a81af12
                - npx rdme@v8 openapi '1.0/importexport.json' --key=$key --id=64634e380dccda005a740517
                - npx rdme@v8 openapi '1.0/inventory.json' --key=$key --id=643e789a87fe590058dbb66c
                - npx rdme@v8 openapi '1.0/listings.json' --key=$key --id=646b2d18f8d2410013e02986
                - npx rdme@v8 openapi '1.0/locations.json' --key=$key --id=645b76cc511cd111e76d6039
                - npx rdme@v8 openapi '1.0/macro.json' --key=$key --id=6454fb0267be7d1325fdea68
                - npx rdme@v8 openapi '1.0/openorders.json' --key=$key --id=64527483b78798006ffc759f
                - npx rdme@v8 openapi '1.0/orders.json' --key=$key --id=645b79922f68af1d0b08fefc
                - npx rdme@v8 openapi '1.0/picking.json' --key=$key --id=6464949a0c297f000b227f40
                - npx rdme@v8 openapi '1.0/postsale.json' --key=$key --id=645386bd51ae010e341ce68a
                - npx rdme@v8 openapi '1.0/postalservices.json' --key=$key --id=645cf4ca59e7a81c99ee340a
                - npx rdme@v8 openapi '1.0/printservice.json' --key=$key --id=64673a39dbf096000a92e442
                - npx rdme@v8 openapi '1.0/processedorders.json' --key=$key --id=64550ce5846bfe155ebe97e6
                - npx rdme@v8 openapi '1.0/purchaseorder.json' --key=$key --id=6453a39d8fb51c001f98ea1f
                - npx rdme@v8 openapi '1.0/returnsrefunds.json' --key=$key --id=6451177fc1d61d0295ff3e6f
                - npx rdme@v8 openapi '1.0/rulesengine.json' --key=$key --id=646761576401c9001297cb22
                - npx rdme@v8 openapi '1.0/settings.json' --key=$key --id=6464ef32f238120ff1559a22
                - npx rdme@v8 openapi '1.0/shippingservice.json' --key=$key --id=645ba12607bd6515d9f529b6
                - npx rdme@v8 openapi '1.0/stock.json' --key=$key --id=643e784d123d7e0025573244
                - npx rdme@v8 openapi '1.0/warehousetransfer.json' --key=$key --id=646605889e893a087456d352
                - npx rdme@v8 openapi '1.0/wms.json' --key=$key --id=64663af3ed0b0308d428071a
